### ISSUE TITLE
HTTP auth causing web-page loading hang 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#101]
Recently I enabled HTTP authentication on the openevse. Occasionally the webpage will hang when trying to login. Just wondering if this could be replicated?

@jeremypoulter have you tested with HTTP authentication enabled?

**Comment by tgould** [comment]
I have experienced this issue and can replicate.  Happens when you use 2 different devices to access the web UI (may only occur if within an Auth Timeout period.)  The first will work and then every attempt after from any other device will fail.  On 2.4.1.  With HTTP Auth fields cleared out, I do not experience it.

**Comment by glynhudson** [comment]
I vote removing HTTP auth to fix this issue since basic HTTP auth over non-SSL connection is basically worthless anyway and could give a user a false sense of security.

**Comment by chris1howell** [comment]
I do not agree, security is achieved by adding layers. HTTP auth is only
useless if someone has enough access to capture and decode packets. Over
the air we have WPA. Over the wire the network should be physically secured
especially in a home. A milicious party would have to compromise a device
that is capible enough to capture and decode packets then catch an
authentication in progress.

Disabling auth would allow RAPI commands to be sent and exicuted without
all the work to compromise the network, capture the password during
authentication then send authenticated packets.

Hopefully a HTTPS server becomes available and then we do not have to worry
about unencrypted authentication.

On Nov 13, 2017 6:52 PM, "Glyn Hudson" <notifications@github.com> wrote:

I vote removing HTTP auth to fix this issue since basic HTTP auth over
non-SSL connection is basically worthless anyway and could give a user a
false sense of security.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/101#issuecomment-344129946>,
or mute the thread

**Comment by glynhudson** [comment]
Valid points @chris1howell. Let's try and fix it rather than remove it.
