### ISSUE TITLE
Add MQTT message format flexibility

### ISSUE THREAD

**Issue by sandeen** [OpenEVSE/ESP8266_WiFi_v2.x#123]
collectd can receive mqtt messages, but only if they are in specific formats.  It infers several things from the topic path, which can be set, but it also expects a timestamp or "N:" in front of the value, i.e.  openevse/openevse/mqtt/amp N:5060

Simply adding another config field to allow an arbitrary string to prefix the value may offer more flexibility for different MQTT subscribers.

**Comment by glynhudson** [comment]
Mmm I personally think that this would be better achieved using something like Node-RED to re-publish the data from the MQTT Node-RED to a new topic with custom parameters. This would give you full customisation and control. 

I'm going to close this issues since IMO there are higher priority issues I would like to focus on atm.
