### ISSUE TITLE
use a minifier on the .js .html files

### ISSUE THREAD

**Issue by davehun** [OpenEVSE/ESP8266_WiFi_v2.x#154]
the src/data contents files are minified in git so they are pretty hard to compare and debug (e.g. spotting changes and regressions).
They should be pretty in the source code and then minified before final upload. This would also make the final files much smaller

**Comment by glynhudson** [comment]
`src/data` is generated from `src/html` on platformio compile. Any changes to `src/data` will be overwritten on next compile. Best to edit `src/html`. 

`src/data` is commited to git (not best practice I realise) to allow easier uploading to ESP

**Comment by jeremypoulter** [comment]
Arduino IDE support rather.

Kind of on this subject, I am not overly happy with how this works, it was
structured to not depend installation of additional tools, ie depend on
Python or online tools. Unfortunately these are not that good and don't
generate map files so it may be nice to move to something for mainstream,
eg https://webpack.js.org, adding a dependency on node.js.

Any thoughts?

On 14 Feb 2018 20:50, "Glyn Hudson" <notifications@github.com> wrote:

src/data is generated from src/html on platformio compile. Any changes to
src/data will be overwritten on next compile. Best to edit src/html.

src/data is commited to git (not best practice I realise) to allow easier
uploading to ESP

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/154#issuecomment-365740812>,
or mute the thread
