### ISSUE TITLE
Add RAPI command to alter divertmode

### ISSUE THREAD

**Issue by colmobri** [OpenEVSE/ESP8266_WiFi_v2.x#176]
I've created a screen using node-red (my first) to integrate the controls and displays for my Growatt battery, EmonPi and OpenEVSE charger and hopefully add some extra intelligence when in divertmode (like using the Growatt battery to assist during peak charge times).  

The one thing I seem unable to do is switch the charger to/from divert mode using RAPI over MQTT.  
Maybe I need to open this issue over on OpenEVSE instead?  
Well done to everyone who has worked on OpenEVSE and OpenEnergyMonitor.  Amazing stuff.

**Comment by jeremypoulter** [comment]
Hi, 

The divert mode is controlled by the WiFi module rather than the OpenEVSE. RAPI is used to control the OpenEVSE module, hence no RAPI command to control the divert, nore does it really make sense to add one.

There is however already a way to remotely control the divert mode both be MQTT and HTTP.

MQTT: {base-topic}/divertmode/set
HTTP POST: http://openevse.local/divertmode

In both cases 1 is normal mode and 2 is divert mode: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/master/src/divert.cpp#L14:L24
