### ISSUE TITLE
Website stops loading and port 80 sporadically unresponsive

### ISSUE THREAD

**Issue by ian-hailey** [OpenEVSE/ESP8266_WiFi_v2.x#186]
Hi, 

After some time (within 24 hours) I find that the ESP8266 gets into an unstable state where it either no longer replies to TCP SYN on port 80 or partially serves the main page when I try to load it via my PC.

In the attached log I notice it is the GET /status that is failing but separately I can issue a curl request (curl 'http://openevse/status') from the same machine to fetch the status and this works.

Rebooting 'fixes' this issue and I find that re-flashing the firmware does not help.

Ian.

[evse_website_load_stuck_tcp.pcapng.zip](https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/files/2086768/evse_website_load_stuck_tcp.pcapng.zip)

**Comment by glynhudson** [comment]
Hi Ian,

Sorry to hear your having issues. I'm unable to replicate.

What version wifi gateway firmware and openevse firmware are you running?
And what hardware esp module are you using? Are you using the standard
power supply? Is the unit in decent WiFi range?

Does the happen every 24hrs?

- sent from my mobile device

**Comment by ian-hailey** [comment]
Hi Glyn, 

HW Firmware: 4.8.0
OpenEVSE Wifi Firmware: 2.7.4
Wifi srssi: -59

I am using the (I assume standard) DC-DC converter power supply from your shop.

Yesterday it did not get into this state but it was in this state again this morning and I had to power cycle the charger.

I have a service on a Linux machine constantly (every 5s) asking for status and periodically updating the charge current via RAPI (SC). In addition I probably leave open one or two web connections from my phone and PC which I suppose also may be requesting status periodically. Could there be either a concurrency issue or race that leads to this lock up perhaps?

Thanks,

Ian.

**Comment by jeremypoulter** [comment]
The web interface is kind of memory hungry, especially if you have multiple
concurrent sessions. Have you tried MQTT for getting the data rather than
the /status? That is a lot more efficient both in terms of resources on the
ESP and you will get the data in a much more timely fashion as it is pushed
to you rather than having to poll for changes.

On 11 Jun 2018 05:48, "ian-hailey" <notifications@github.com> wrote:

Hi Glyn,

HW Firmware: 4.8.0
OpenEVSE Wifi Firmware: 2.7.4
Wifi srssi: -59

I am using the (I assume standard) DC-DC converter power supply from your
shop.

Yesterday it did not get into this state but it was in this state again
this morning and I had to power cycle the charger.

I have a service on a Linux machine constantly (every 5s) asking for status
and periodically updating the charge current via RAPI (SC). In addition I
probably leave open one or two web connections from my phone and PC which I
suppose also may be requesting status periodically. Could there be either a
concurrency issue or race that leads to this lock up perhaps?

Thanks,

Ian.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/186#issuecomment-396215927>,
or mute the thread

**Comment by ian-hailey** [comment]
Hi Jeremy, using MQTT is probably a better solution although I would have to increase the update rate a bit as it looks like it's pushing updates every 30s?

I notice that the ESP can serve 3 concurrent connections to the main website, the 4th attempt fails. It would nice if new connections would kick off oldest one if there are more then 3, this would avoid the site ever from going down.

**Comment by jeremypoulter** [comment]
I will take a look at the web server again, always worth revisiting.

The update time for HTTP and MQTT is the same BTW. The /status endpoint
just  retrieves the cached values from when they where last fetched for
MQTT. There ticket about increasing the update period and I think we are at
a reasonable place to be able to do that.
