### ISSUE TITLE
ESP8266 MQTT RAPI polling results in the unit hanging

### ISSUE THREAD

**Issue by paulbernardr** [OpenEVSE/ESP8266_WiFi_v2.x#218]
Hi
Using a python script, I have tried to use the MQTT RAPI request $G0 to tell me if an EV is connected to the EVSE. However after a few hundred requests, spaced by 30sec, the response on openevse/rapi/out stops working and usually the unit hangs completely.  I'm running the latest firmware 2.7.8
I have tried all sorts of permutations to try get this to stay operational but to no avail. 
Paul

**Comment by jeremypoulter** [comment]
Hi, i guess there is some memory leak, however I am not sure this use of MQTT is the best way to accomplish the goal.

MQTT is a message broker so is inherently designed for notifications to be pushed, no need to poll. So to get the state change just subscribe to `openevse/state` and you will be notified within ms of the state change, rather than up to 29.99999 seconds after it has happened.

If there is a reason why you have to use polling, then I would suggest maybe try the HTTP API (http://openevse.local/r) this is a lot better suited to being used in that manor, RAPI over MQTT is a bit of a cludge due to the fact that that is not really how MQTT should be used.
