### ISSUE TITLE
Replicate OpenEVSE local (LCD) controls on web UI

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#34]
All the controls on the OpenEVSE LCD should be available on the web UI with a focus on;

- [x] Change charge current limit
- [x] Set the time limit
- [x] Set energy limit 
- [x] Set charging timer 
- [x] Setting the current time, see #15 
- [x] Set the service Level
    - Use location to set appropriately for the region?

**Comment by glynhudson** [comment]
Yes, service level will always be L2 in countries that have 240V. In The USA is could be L1 or L2 depending on the outlet it's plugged into. However, I guessing most (if not all) users will be using L2 from 240V outlets since much of the benefit of using a unit like the OpeneEVSE if it's connected  110V  outlet. What do you think @chris1howell

**Comment by chris1howell** [comment]
Most of the world will be L2 only, in the US and other countries that use 120 and 240v L2 will be used most often. Many users in the US build the kit that can support both and OpenEVSE will be set to auto. The most common settings are L2 only or Auto. L1 only is rarely used.

I do not think there is much benefit to set by region, it is best to just use the default from firmware and allow the user to change if necessary.

On Wed, May 31, 2017 at 8:35 AM, Glyn Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, service level will always be L2 in countries that have 240V. In The USA is could be L1 or L2 depending on the outlet it's plugged into. However, I guessing most (if not all) users will be using L2 from 240V outlets since much of the benefit of using a unit like the OpeneEVSE if it's connected 110V outlet. What do you think @chris1howell<https://github.com/chris1howell>

**Comment by jeremypoulter** [comment]
All changes now implemented in #51
